services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Hoogi91\Spreadsheets\:
    resource: '../Classes/*'

  Hoogi91\Spreadsheets\DataProcessing\SpreadsheetProcessor:
    public: true
