name: 'Checkout and run composer'
description: 'This action checks out the commit, sets up PHP and installs deps using composer.'
inputs:
  php-version:
    required: true
    description: 'PHP Version to use'
  extensions:
    required: false
    description: 'PHP extensions to install'
    default: ''
  dependencies:
    required: false
    description: 'Instruction which composer dependencies to install - one of "highest", "lowest", defaults to "locked"'
    default: 'locked'
runs:
  using: 'composite'
  steps:
    - name: "Checkout"
      uses: "actions/checkout@v2"

    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        coverage: "pcov"
        php-version: "${{ inputs.php-version }}"
        ini-values: memory_limit=-1
        tools: composer:v2, cs2pr
        extensions: "${{ inputs.extensions }}"

    - name: "Cache dependencies"
      uses: "actions/cache@v2"
      with:
        path: |
          ~/.composer/cache
          vendor
        key: "php-${{ inputs.php-version }}-${{ inputs.dependencies }}"
        restore-keys: "php-${{ inputs.php-version }}-${{ inputs.dependencies }}"

    - name: "Install lowest dependencies"
      if: ${{ inputs.dependencies == 'lowest' }}
      run: "composer update --prefer-lowest --no-interaction --no-progress --no-suggest --ignore-platform-req=php"

    - name: "Install highest dependencies"
      if: ${{ inputs.dependencies == 'highest' }}
      run: "composer update --no-interaction --no-progress --no-suggest --ignore-platform-req=php"

    - name: "Install locked dependencies"
      if: ${{ inputs.dependencies == 'locked' }}
      run: "composer install --no-interaction --no-progress --no-suggest --ignore-platform-req=php"
