name: "Dependabot auto-approve"

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: "Dependabot auto-approve"
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Approve Dependabot PRs
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
