name: "Static analysis"

on:
  pull_request:
  push:

jobs:
  static-analysis:
    name: "Static analysis"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: Checkout and composer install
        uses: ./.github/actions/php-checkout-and-composer
        with:
          php-version: '${{ matrix.php_version }}'
          dependencies: '${{ matrix.dependencies }}'
          extensions: json, mbstring

      - name: PHPStan
        run: vendor/bin/phpstan analyse --level 5 Classes/
